version: '3.9'
services:
  web:
    build: .
    entrypoint: |
      pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple && \
      pip install --no-cache-dir uvicorn[standard] fastapi -i https://pypi.tuna.tsinghua.edu.cn/simple && \
      pip install --no-cache-dir sentence-transformers -i https://pypi.tuna.tsinghua.edu.cn/simple && \
      uvicorn main:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "8890:80"
    env_file:
      - .env

    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

